### ISSUE TITLE
Presence of Obsidian Legend savegames causes freeze on clicking Load button

### ISSUE THREAD

**Issue by jkatzmewing** [Beamdog/nwn-issues#600]
**To Reproduce**

1. Install the latest CEP 2 and The Obsidian Legend (https://neverwintervault.org/project/nwn1/module/obsidian-legend-story-module-snottling)
2. Start a game in The Obsidian Legend and save.
3. Close NWN, reopen, and click Load. It should freeze immediately.

**Crash Dump**

The crash log is zero length. GDB backtrace looks like this:

```
#0  0x00007ffff79aae2c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff795bfb2 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7946472 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff799f430 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff79b47aa in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007ffff79b789c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007ffff79b96e2 in calloc ()
   from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007fffee542222 in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#8  0x00007fffee5426da in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#9  0x0000555555874eac in CAurTextureBasic::glImageBasic(bool) ()
#10 0x0000555555875f6d in CAurTextureBasic::BuildAndStoreTexture() ()
#11 0x0000555555877f3b in AurTextureBuildAndStoreAll() ()
#12 0x0000555555878099 in AurTextureMakeCurrent() ()
#13 0x0000555555860b1b in Scene::Render() ()
#14 0x000055555588ba27 in Camera::RenderScene() ()
#15 0x00005555559308d6 in CGuiMan::UpdateAndRender(float) ()
#16 0x00005555559e50b4 in CClientExoAppInternal::MainLoop() ()
#17 0x00005555558203f6 in Update(void*) ()
#18 0x000055555580b5a7 in main ()
```

**Specifics**

 - OS: Debian 12.5 with backported kernel, using Lutris flatpak
 - Game build: 05285dea198156d7b301ad9d4502e9eaa5c0b58e
 - Distro platform: GOG
 - Repro Rate: 100%
 - Content overrides: Gunner's Bodies and Cattaneo's Portrait Pack, but I can reproduce the crash without these

**Comment by jkatzmewing** [comment]
Duplicate of https://github.com/Beamdog/nwn-issues/issues/514, this was in fact a portrait problem. The problem saves contain corrupt portrait.tga files.
